### ISSUE TITLE
Adding rust-lang support

### ISSUE THREAD

**Issue by c12i** [paulonteri/remote-code-execution-environment#6]
Impressive project! I am interested in adding support for the [Rust](https://www.rust-lang.org/) programming language.

I have tested out installation of two alpine packages to the Docker image with positive results: [`rust`](https://pkgs.alpinelinux.org/package/edge/community/x86_64/rust) and [`cargo`](https://pkgs.alpinelinux.org/package/edge/community/x86_64/cargo).

**Describe the solution you'd like**
* Work on a Rust service module to compile and run rust code.
* Accommodate new changes to the frontend app

**Additional context**.
Feel free to assign the issue

**Comment by paulonteri** [comment]
Thank you! Please do. 

I, unfortunately, don't have any guides on how to add a language but checking out how I implemented [`Python`](https://github.com/paulonteri/remote-code-execution-environment/blob/staging/core/services/python.js) and [`Java`](https://github.com/paulonteri/remote-code-execution-environment/blob/staging/core/services/java.js) can give you an idea.

Once done just make a PR to the staging branch.

**Comment by c12i** [comment]
Yea, will use existing code for reference, consider adding those instructions to the docs
